repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml

  -   repo: https://github.com/pre-commit/mirrors-csslint
      rev: v1.0.5
      hooks:
        - id: csslint

  -   repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v7.32.0'
      hooks:
        -   id: eslint