repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.12.0
    hooks:
      - id: jshint
